### ISSUE TITLE
Can't config the server

### ISSUE THREAD

**Issue by LeVeloute** [Zuluru/Zuluru3#3] opened 2019-02-27 13:11 UTC
Hi,
I got a problem during the configuration of the server.
I can't access the page ( https://tournoi.ces-esport.fr/installer/install ).
And when i try to go to the index i got an error 500. ( https://tournoi.ces-esport.fr ).

Here are the log from my webserver : 

`PHP message: PHP Fatal error:  [Cake\Database\Exception\MissingDriverException] Database driver Cake\Database\Driver\ could not be found.
#0 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/Database/Connection.php(120): Cake\Database\Connection->setDriver('Cake\\Database\\D...', Array)
#1 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/Datasource/ConnectionRegistry.php(89): Cake\Database\Connection->__construct(Array)
#2 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php(97): Cake\Datasource\ConnectionRegistry->_create('Cake\\Database\\C...', 'default', Array)
#3 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/Datasource/ConnectionManager.php(205): Cake\Core\ObjectRegistry->load('Cake\\Database\\C...', Array)
#4 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php(216): Cake\Datasource\ConnectionManager::get('default')
#5 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/Http/Session/DatabaseSession.php(6...
27/Feb/2019:14:06:45 +0100 [ERROR 0 /] PHP message: PHP Notice:  date_default_timezone_set(): Timezone ID '' is invalid in /var/www/tournoi.ces-esport.fr/config/bootstrap.php on line 117
PHP message: PHP Fatal error:  [Cake\Database\Exception\MissingDriverException] Database driver Cake\Database\Driver\ could not be found.
#0 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/Database/Connection.php(120): Cake\Database\Connection->setDriver('Cake\\Database\\D...', Array)
#1 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/Datasource/ConnectionRegistry.php(89): Cake\Database\Connection->__construct(Array)
#2 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php(97): Cake\Datasource\ConnectionRegistry->_create('Cake\\Database\\C...', 'default', Array)
#3 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/Datasource/ConnectionManager.php(205): Cake\Core\ObjectRegistry->load('Cake\\Database\\C...', Array)
#4 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php(216): Cake\Datasource\ConnectionManager::get('default')
#5 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/Http/Session/DatabaseSession.php(6...
PHP message: PHP Fatal error:  [Cake\Database\Exception\MissingDriverException] Database driver Cake\Database\Driver\ could not be found.
#0 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/Database/Connection.php(120): Cake\Database\Connection->setDriver('Cake\\Database\\D...', Array)
#1 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/Datasource/ConnectionRegistry.php(89): Cake\Database\Connection->__construct(Array)
#2 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php(97): Cake\Datasource\ConnectionRegistry->_create('Cake\\Database\\C...', 'default', Array)
#3 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/Datasource/ConnectionManager.php(205): Cake\Core\ObjectRegistry->load('Cake\\Database\\C...', Array)
#4 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php(216): Cake\Datasource\ConnectionManager::get('default')
#5 /var/www/tournoi.ces-esport.fr/vendor/cakephp/cakephp/src/Http/Session/DatabaseSession.php(6...
`
I don't know what to do to fix this 😢 
Can you help me ?

Thanks by advance.

**Comment by Zuluru** [comment] 2019-02-27 17:52
What version of the code do you have (last few lines of config/bootstrap.php)? There was a bug like this in 3.0.0, but I thought it was fixed in 3.1.1.

**Comment by LeVeloute** [comment] 2019-02-27 18:09
I got the 3.1.1.
How to solve this bug ?

**Comment by Zuluru** [comment] 2019-02-27 18:13
You didn't by any chance manually copy `config/.env.default` to `config/.env` before running the installation?

**Comment by LeVeloute** [comment] 2019-02-27 18:17
Okaaaay, just 
Some appear now. But still 500 error :D

**Comment by Zuluru** [comment] 2019-02-27 18:47
No, that file *shouldn't* be manually copied. People have done so in the past, with results similar to what you're seeing. There should be no `config/.env` file before you run the installer.

I'll have to see if I can reproduce this, but I'm pretty swamped for the next few days unfortunately.

**Comment by LeVeloute** [comment] 2019-02-27 19:12
Okay, i'm waiting for a fix so.
I'm running an esport non profit, and all the team is exicted about trying your work in a tournament !

**Comment by LeVeloute** [comment] 2019-03-12 16:04
Hello,
Have you find a fix? :) 

Best regards,
Paul

**Comment by Zuluru** [comment] 2019-03-12 16:44
Not yet. :-( Finishing up stuff for an unrelated demo today, should have time to get back to this in the next day or two.

**Comment by Zuluru** [comment] 2019-03-15 03:32
Ran an installation from scratch today, and it worked fine. To confirm, this happens right away on the first load of the install page, you don't even get the confirmation page that tells you that your server details match requirements? What version of PHP and MySQL are you running this on?

**Comment by Zuluru** [comment] 2019-03-17 17:37
I think I have a fix for this. Seems it's a problem that happens when you try to *re-run* the installation. This is prevented by the system, because there is obviously no authentication on the installation process, and letting just anyone run it would result in loss of data. So, if you ever need to legitimately re-run the installation, you should:

1. Remove `config/.env` and `config/app_local.php`
2. Edit `vendor/cakephp-app-installer/installer/config/bootstrap.php` and change it to `Configure::write('Database.installed', false);`
3. Purge the database (drop all tables)

Then, you should be able to get to `/installer/install` again.

**Comment by Zuluru** [comment] 2019-04-16 23:54
Did this help you to resolve the issue?

**Comment by Zuluru** [comment] 2019-07-11 01:00
Closing due to lack of response; assuming the fix worked.

**Closed by Zuluru** 2019-07-11 01:00 UTC
